# Generated by Django 5.0.14 on 2026-01-24 04:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Name shown on posts (e.g., 'Ms. Johnson')",
                        max_length=100,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="Contact email address",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "position_role",
                    models.CharField(
                        blank=True,
                        help_text="Job title/role (e.g., 'Teacher', 'Parent', 'Administrator')",
                        max_length=100,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="User's first name", max_length=50),
                ),
                (
                    "last_name",
                    models.CharField(help_text="User's last name", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.RenameIndex(
            model_name="entry",
            new_name="timeline_en_timesta_a3fbb0_idx",
            old_name="timeline_en_timesta_idx",
        ),
        migrations.RenameIndex(
            model_name="entry",
            new_name="timeline_en_user_id_95be14_idx",
            old_name="timeline_en_user_ti_idx",
        ),
        migrations.AlterField(
            model_name="formtype",
            name="name",
            field=models.CharField(
                help_text="Display name (e.g., 'School Day', 'Photo')", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
