# Generated by Django 5.2.10 on 2026-01-25 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0002_userprofile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ["-is_pinned", "-timestamp"],
                "verbose_name": "Entry",
                "verbose_name_plural": "Entries",
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="is_pinned",
            field=models.BooleanField(
                default=False, help_text="Pin this entry to the top of the timeline"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_pin_posts",
            field=models.BooleanField(
                default=False,
                help_text="Allow this user to pin posts to the top of the timeline",
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["-is_pinned", "-timestamp"],
                name="timeline_en_is_pinn_8ba7a5_idx",
            ),
        ),
    ]
