# Generated by Django 5.2.10 on 2026-01-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0004_userprofile_can_delete_any_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_pin_any_post",
            field=models.BooleanField(
                default=False,
                help_text="Allow this user to pin any post, not just their own",
            ),
        ),
    ]
