# Generated by Django 5.2.10 on 2026-01-27 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0005_userprofile_can_pin_any_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EddieProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="General information about Eddie (age, family, personality)"
                    ),
                ),
                (
                    "tips_and_tricks",
                    models.TextField(
                        help_text="Calming strategies, what helps when overwhelmed"
                    ),
                ),
                (
                    "favorites",
                    models.TextField(
                        help_text="Eddie's favorite activities, foods, games, etc."
                    ),
                ),
                (
                    "fun_facts",
                    models.TextField(
                        help_text="Fun and interesting things about Eddie"
                    ),
                ),
                (
                    "goals",
                    models.TextField(
                        help_text="Current developmental and educational goals"
                    ),
                ),
                (
                    "meals_info",
                    models.TextField(
                        help_text="Eating habits, food preferences, dietary notes"
                    ),
                ),
                (
                    "potty_info",
                    models.TextField(help_text="Bathroom routine, assistance needed"),
                ),
                (
                    "safety_info",
                    models.TextField(
                        help_text="Safety considerations, supervision needs"
                    ),
                ),
                (
                    "communication_info",
                    models.TextField(
                        help_text="How Eddie communicates, AAC usage, verbal abilities"
                    ),
                ),
                (
                    "height",
                    models.CharField(
                        blank=True,
                        help_text="Height (e.g., '3 ft 8 in')",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, help_text="Weight (e.g., '45 lbs')", max_length=20
                    ),
                ),
                (
                    "hair_color",
                    models.CharField(blank=True, help_text="Hair color", max_length=50),
                ),
                (
                    "eye_color",
                    models.CharField(blank=True, help_text="Eye color", max_length=50),
                ),
                (
                    "distinguishing_marks",
                    models.TextField(
                        blank=True, help_text="Any distinguishing marks or features"
                    ),
                ),
                (
                    "contact_1_name",
                    models.CharField(
                        help_text="Contact 1 name (e.g., 'Mom')", max_length=100
                    ),
                ),
                (
                    "contact_1_relationship",
                    models.CharField(help_text="Relationship to Eddie", max_length=50),
                ),
                (
                    "contact_1_phone",
                    models.CharField(help_text="Phone number", max_length=20),
                ),
                (
                    "contact_1_email",
                    models.EmailField(
                        blank=True, help_text="Email address (optional)", max_length=254
                    ),
                ),
                (
                    "contact_2_name",
                    models.CharField(
                        help_text="Contact 2 name (e.g., 'Dad')", max_length=100
                    ),
                ),
                (
                    "contact_2_relationship",
                    models.CharField(help_text="Relationship to Eddie", max_length=50),
                ),
                (
                    "contact_2_phone",
                    models.CharField(help_text="Phone number", max_length=20),
                ),
                (
                    "contact_2_email",
                    models.EmailField(
                        blank=True, help_text="Email address (optional)", max_length=254
                    ),
                ),
                (
                    "contact_3_name",
                    models.CharField(
                        blank=True,
                        help_text="Contact 3 name (optional)",
                        max_length=100,
                    ),
                ),
                (
                    "contact_3_relationship",
                    models.CharField(
                        blank=True, help_text="Relationship to Eddie", max_length=50
                    ),
                ),
                (
                    "contact_3_phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20
                    ),
                ),
                (
                    "contact_3_email",
                    models.EmailField(
                        blank=True, help_text="Email address (optional)", max_length=254
                    ),
                ),
                (
                    "contact_4_name",
                    models.CharField(
                        blank=True,
                        help_text="Contact 4 name (optional)",
                        max_length=100,
                    ),
                ),
                (
                    "contact_4_relationship",
                    models.CharField(
                        blank=True, help_text="Relationship to Eddie", max_length=50
                    ),
                ),
                (
                    "contact_4_phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20
                    ),
                ),
                (
                    "contact_4_email",
                    models.EmailField(
                        blank=True, help_text="Email address (optional)", max_length=254
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this profile",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Eddie's Profile",
                "verbose_name_plural": "Eddie's Profile",
            },
        ),
    ]
