# Generated by Django 5.2.10 on 2026-01-27 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0006_eddieprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="eddieprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Current photo of Eddie for caregivers",
                null=True,
                upload_to="eddie_profile/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif", "webp"]
                    )
                ],
            ),
        ),
    ]
