# Generated by Django 5.2.10 on 2026-01-30 17:08

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0007_eddieprofile_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this token (e.g., 'Life360 Integration')",
                        max_length=100,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        help_text="Secret token included in webhook URLs",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Disable to revoke access without deleting",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="Last time this token was used", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Token",
                "verbose_name_plural": "Webhook Tokens",
            },
        ),
    ]
