# Generated by Django 5.2.10 on 2026-01-30 17:08

from django.db import migrations


def create_webhook_dependencies(apps, schema_editor):
    """
    Create the System user, Location form type, and an initial webhook token.
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('timeline', 'UserProfile')
    FormType = apps.get_model('timeline', 'FormType')
    WebhookToken = apps.get_model('timeline', 'WebhookToken')

    # Create System user (if not exists)
    from django.contrib.auth.hashers import make_password
    system_user, created = User.objects.get_or_create(
        username='system',
        defaults={
            'first_name': 'System',
            'last_name': '',
            'is_active': False,  # Cannot log in
            'password': make_password(None),  # Unusable password
        },
    )

    # Create System user profile (if not exists)
    UserProfile.objects.get_or_create(
        user=system_user,
        defaults={
            'display_name': 'Location Tracker',
            'email_address': 'system@localhost',
            'first_name': 'System',
            'last_name': '',
            'position_role': 'Automated System',
        },
    )

    # Create Location form type (if not exists)
    FormType.objects.get_or_create(
        type='location',
        defaults={
            'name': 'Location',
            'icon': '\U0001F4CD',  # 📍 round pushpin / map pin
            'description': 'Automated location tracking via webhooks',
            'is_active': True,
            'is_default': False,
        },
    )

    # Create an initial webhook token
    import secrets
    WebhookToken.objects.get_or_create(
        name='Default Webhook Token',
        defaults={
            'token': secrets.token_urlsafe(32),
            'is_active': True,
        },
    )


def reverse_webhook_dependencies(apps, schema_editor):
    """
    Reverse: remove the webhook-specific data.
    """
    User = apps.get_model('auth', 'User')
    FormType = apps.get_model('timeline', 'FormType')
    WebhookToken = apps.get_model('timeline', 'WebhookToken')

    WebhookToken.objects.filter(name='Default Webhook Token').delete()
    FormType.objects.filter(type='location').delete()
    User.objects.filter(username='system').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0008_add_webhook_token"),
    ]

    operations = [
        migrations.RunPython(
            create_webhook_dependencies,
            reverse_webhook_dependencies,
        ),
    ]
