# Generated by Django 5.0.14 on 2026-02-04 17:59
# Modified to use RenameModel to preserve data

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeline", "0009_setup_webhook_data"),
    ]

    operations = [
        # Step 1: Rename the model (preserves all data)
        migrations.RenameModel(
            old_name="EddieProfile",
            new_name="ChildProfile",
        ),
        # Step 2: Add the child_name field
        migrations.AddField(
            model_name="childprofile",
            name="child_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Child's name (displayed throughout the app)",
                max_length=100,
            ),
        ),
        # Step 3: Update the photo field (change upload_to path)
        migrations.AlterField(
            model_name="childprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Current photo for caregivers",
                null=True,
                upload_to="child_profile/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "gif", "webp"]
                    )
                ],
            ),
        ),
        # Step 4: Update help_text on various fields
        migrations.AlterField(
            model_name="childprofile",
            name="bio",
            field=models.TextField(
                help_text="General information (age, family, personality)"
            ),
        ),
        migrations.AlterField(
            model_name="childprofile",
            name="favorites",
            field=models.TextField(
                help_text="Favorite activities, foods, games, etc."
            ),
        ),
        migrations.AlterField(
            model_name="childprofile",
            name="fun_facts",
            field=models.TextField(help_text="Fun and interesting things to know"),
        ),
        migrations.AlterField(
            model_name="childprofile",
            name="communication_info",
            field=models.TextField(
                help_text="How they communicate, AAC usage, verbal abilities"
            ),
        ),
        migrations.AlterField(
            model_name="childprofile",
            name="contact_1_relationship",
            field=models.CharField(help_text="Relationship", max_length=50),
        ),
        migrations.AlterField(
            model_name="childprofile",
            name="contact_2_relationship",
            field=models.CharField(help_text="Relationship", max_length=50),
        ),
        migrations.AlterField(
            model_name="childprofile",
            name="contact_3_relationship",
            field=models.CharField(
                blank=True, help_text="Relationship", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="childprofile",
            name="contact_4_relationship",
            field=models.CharField(
                blank=True, help_text="Relationship", max_length=50
            ),
        ),
        # Step 5: Update model options (verbose_name)
        migrations.AlterModelOptions(
            name="childprofile",
            options={
                "verbose_name": "Child Profile",
                "verbose_name_plural": "Child Profile",
            },
        ),
    ]
